#!/usr/bin/fish
# Script for spreading or collecting the dotfiles into their git repo dir

# List all files to copy in to or out from homedir
set files .vimrc .gvimrc .vim .gitconfig .config/fish/config.fish .Xdefaults .dwmsb .tmux.conf .Xmodmap .xinitrc .xbindkeysrc .switchxkbmap .xpdfrc .dwmsb-mail

switch "$argv[1]"
  case "in"
    echo "This will overwrite files in the repo. Please confirm (y/n):"
  case "out"
    echo "This will overwrite files IN YOUR HOMEDIR. Please confirm (y/n):"
  case "*"
    echo "Usage: copy in   - collect from homedir"
    echo "       copy out  - spread to homedir"
    exit 1
end
  
read confirm
if test $confirm != "y"
  exit 0
end


for f in $files
  if test $argv[1] = "in" 
    cp -r ~/$f ./$f
  end
  if test $argv[1] = "out"
    cp -r ./$f ~/$f
  end
end
