#!/usr/bin/fish
# List all files to copy in to or out from homedir
set files .vimrc .gvimrc .gitconfig .config/fish/config.fish .Xdefaults

if test (count $argv) -lt 1
  echo "Usage: copy in   - collect from homedir"
  echo "       copy out  - spread to homedir"
  exit 1
end

echo "This will overwrite files. Please confirm (y/n):"
read confirm
if test $confirm != "y"
  exit 0
end


for f in $files
  if test $argv[1] = "in" 
    cp ~/$f ./$f
  end
  if test $argv[1] = "out"
    cp ./$f ~/$f
  end
end
echo "Note: Not touching /etc/hosts"
