#!/usr/bin/fish
# Script for spreading or collecting the dotfiles into their git repo dir

# Full directories
set dirs .vim/

# The usual stuff
set files        .vimrc
set files $files .gitconfig
set files $files .ctags
set files $files .iftoprc
set files $files .taskrc
set files $files .tmux.conf

# Custom awesomeness
set files $files .bg/setbg.py
set files $files .dwmsb.py

# Fish
set files $files .config/fish/config.extract
set files $files .config/fish/config.fish.example
set files $files .config/fish/config.pacman
set files $files .config/fish/config.prompt
set files $files .config/fish/config.shortcuts

# X11
set files $files .Xresources
set files $files .Xmodmap
set files $files .xinitrc
set files $files .xbindkeysrc
set files $files .xpdfrc

# Copy logic

switch "$argv[1]"
  case "in"
    echo "This will overwrite files in the repo. Please confirm (y/n):"
  case "out"
    echo "This will overwrite files IN YOUR HOMEDIR. Please confirm (y/n):"
  case "*"
    echo "Usage: copy in   - collect from homedir"
    echo "       copy out  - spread to homedir"
    exit 1
end

read confirm
if test $confirm != "y"
  exit 0
end


for d in $dirs
  if test $argv[1] = "in"
    cp -r ~/$d ./
  end
  if test $argv[1] = "out"
    cp -r ./$d ~
  end
end

for f in $files
  if test $argv[1] = "in"
    cp -r ~/$f ./$f
  end
  if test $argv[1] = "out"
    cp -r ./$f ~/$f
  end
end
