#!/usr/bin/fish
# Displays some hand-picked data values in the dwm status bar

# Mail status
cat ~/.dwmsb/mail-status | tr -d '\n'

# if discharging, show remaining power
if test (cat /proc/acpi/battery/BAT0/state | grep charging | awk '{print $3}') != 'charged'
  echo -n (cat /proc/acpi/battery/BAT0/state | grep remaining | awk '{print $3}')
  echo -n " | "
end

# cpu temp
sensors | grep temp1 | awk '{print $2}' | sed 's/+//' | sed 's/..°C//' | tr -d '\n'
echo -n " | "

# mem usage
free -b | awk 'NR == 2 { print int(int(0.5 + 1000 * ($3 - ($6 + $7)) / $2)/10) }' | tr -d '\n'
echo -n "% | "

# disk usage
df -h | grep sda4 | awk '{ print $3 "/" $2 }' | sed 's/G//g' | tr -d '\n'
echo -n " | "

# load avg
cat /proc/loadavg | cut -d ' ' -f 1,2,3 | tr -d '\n'
echo -n " | "

# current date
echo -n (date +"%F %W %R")
