import = ["/home/ali/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[font]
size = 12.0

[font.bold]
family = "DejaVu Sans Mono"

[font.bold_italic]
family = "DejaVu Sans Mono"

[font.italic]
family = "DejaVu Sans Mono"

[font.normal]
family = "DejaVu Sans Mono"
